fails to compile due to typo in includes
Fails to compile with error.
part7_teleport.cpp: In member function ‘virtual void Player::Chat(const char*)’:
part7_teleport.cpp:18:29: error: ‘strncmp’ was not declared in this scope
     if(strncmp("tp ", msg, 3) == 0) {
                             ^
changing #include <string> 
to 
#include <string.h>
allows me to compile.